/**
 * MangaDex language codes
 * @enum {String}
 */
module.exports = {
    SA: "Arabic",
    BD: "Bengali",
    BG: "Bulgarian",
    MM: "Burmese",
    CT: "Catalan",
    CN: "Chinese (Simp)",
    HK: "Chinese (Trad)",
    CZ: "Czech",
    DK: "Danish",
    NL: "Dutch",
    GB: "English",
    PH: "Filipino",
    FI: "Finnish",
    FR: "French",
    DE: "German",
    GR: "Greek",
    HU: "Hungarian",
    ID: "Indonesian",
    IT: "Italian",
    JP: "Japanese",
    KR: "Korean",
    LT: "Lithuanian",
    MY: "Malay",
    MN: "Mongolian",
    IR: "Persian",
    PL: "Polish",
    BR: "Portuguese (Br)",
    PT: "Portuguese (Pt)",
    RO: "Romanian",
    RU: "Russian",
    RS: "Serbo-Croatian",
    ES: "Spanish (Es)",
    MX: "Spanish (LATAM)",
    SE: "Swedish",
    TH: "Thai",
    TR: "Turkish",
    UA: "Ukrainian",
    VN: "Vietnamese"
};